Loading model from /home/riyasatohib_cohere_com/repos/models/meta-llama/Meta-Llama-3-8B...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.08it/s]
Traceback (most recent call last):
  File "/home/riyasatohib_cohere_com/repos/teal_clone/regularization/finetune.py", line 224, in <module>
    main()
  File "/home/riyasatohib_cohere_com/repos/teal_clone/regularization/finetune.py", line 197, in main
    model, optimizer, train_dataloader, scheduler = accelerator.prepare(
                                                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/riyasatohib_cohere_com/.conda/envs/teal/lib/python3.11/site-packages/accelerate/accelerator.py", line 1300, in prepare
    raise ValueError(
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/riyasatohib_cohere_com/repos/teal_clone/regularization/finetune.py", line 224, in <module>
[rank1]:     main()
[rank1]:   File "/home/riyasatohib_cohere_com/repos/teal_clone/regularization/finetune.py", line 197, in main
[rank1]:     model, optimizer, train_dataloader, scheduler = accelerator.prepare(
[rank1]:                                                     ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/riyasatohib_cohere_com/.conda/envs/teal/lib/python3.11/site-packages/accelerate/accelerator.py", line 1300, in prepare
[rank1]:     raise ValueError(
[rank1]: ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
